import setuptools
setuptools.setup(
    name="Game_Net",
    version='0.0.1',
    author="HectorHe",
    author_email="zhilinhe@usc.edu",
    entry_points={
        'console_scripts': [
            'manager = manager:main',
            'fetch = services.data_fetcher:main'
        ]
    },
    license="MIT",
    packages=setuptools.find_packages(),
    install_requires=[
        'simplejson==3.17.6',
        "beautifulsoup4>=4.9.1",
        "lxml>=4.2.1",
        "requests>=2.22.0",
        "pypinyin>=0.35.0",
        "html5lib>=1.0.1",
        "xlrd>=1.2.0",
        "urllib3>=1.25.8",
        "tqdm>=4.43.0",
        "openpyxl>=3.0.3",
        "jsonpath>=0.82",
        "tabulate>=0.8.6",
        "decorator>=4.4.2",
        "py_mini_racer>=0.6.0",
        "requests-cache>=0.9.3",
        'ujson==5.1.0',
        'redis==4.2.1',
        'requests==2.27.1',
        'aiohttp==3.8.1',
        'websocket-client==0.57.0',
        'flask==2.0.3',
        'greenlet==1.1.2',
        'gevent==21.12.0',
        'pandas==1.4.1',
        'numpy==1.22.3',
        'fire==0.4.0',
        'python-crontab==2.6.0',
        'sqlalchemy==1.4.29',
        'joblib==1.1.0',
        'psycopg2-binary==2.9.3',
        'pytest==7.1.1',
        'pytest-order==1.0.1',
        'cryptography==3.4.7',
        'flask-cors==3.0.10',
        'tushare==1.2.85',
        'jqdatasdk==1.8.10'
    ],
    package_data={"": ["*.py", "*.json", "*.pk", "*.js"]},
    python_requires=">=3.7",
)